# name: Terraform Deploy

# on:
#   push:
#     branches: [ bckup-vm ]

# jobs:
#   terraform:
#     name: "Terraform Apply"
#     runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: read

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Authenticate to GCP via Workload Identity Federation
#       uses: google-github-actions/auth@v2
#       with:
#         workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
#         service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: 1.6.6

#     - name: Terraform Init
#       run: terraform init

#     - name: Terraform Plan
#       run: terraform plan -var="project_id=${{ vars.GCP_PROJECT_ID }}"

#     - name: Terraform Apply
#       run: terraform apply -auto-approve -var="project_id=${{ vars.GCP_PROJECT_ID }}"
